const router = require('express').Router();
import * as user from './controllers/user.controller';
import * as deck from './controllers/deck.controller';
import * as card from './controllers/card.controller';

//USER - ROUTES
router.post('/user', user.createUser);
router.get('/user', user.getAllUsers);
router.get('/user/:userUID', user.getUserByUUId);
router.get('/user/userId/:id', user.getUserById);
router.get('/user/userEmail/:email', user.getUserByEmail);
router.put('/user/:id', user.updateUser); // :id -> user id automatically generated by sequelize
router.delete('/user/:id', user.deleteUser);

//DECK - ROUTES
router.post('/deck', deck.createDeck);
router.get('/deck', deck.getAllDecks);
router.get('/deck/:userId', deck.getAllDecksByUserId);
router.put('/deck/:id', deck.updateDeck); // :id -> deck id automatically generated by sequelize
router.delete('/deck/:id', deck.deleteDeck);

//CARD - ROUTES
router.post('/card', card.createCard);
router.get('/card', card.getAllCards);
router.get('/card/:deckId', card.getAllDecksByDeckId);
router.put('/card/:id', card.updateCard); // :id -> card id automatically generated by sequelize
router.delete('/card/:id', card.deleteCard);

export default router;
